### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by HarlanZhou** [IvanoLauriola/MKLpy#13]
When i type "from MKLpy.algorithms import AverageMKL, EasyMKL, KOMD",  "ImportError: DLL load failed: 找不到指定的模块" what should I fix?

**Comment by IvanoLauriola** [comment]
Hi,
I just tried with the current version (0.4.3), and the previous one (0.4.2). 
I did not replicate the error.
I suggest you to check the installation of CVXOPT. If the problem is not CVXOPT please give us additional details (os, software version, and full stacktrace)
