### ISSUE TITLE
Need a suggestion.

### ISSUE THREAD

**Issue by dmc-8288** [IvanoLauriola/MKLpy#14]
I know that cross_value_score function internally uses K-fold method, but I want to use leave one out cross-validation method. So my question is how can I do it?
Your suggestion might help me.

**Comment by IvanoLauriola** [comment]
Hi,
that part (i.e. model selection) is currently not documented at all. 
We'll provide a concrete set of examples by tomorrow, thanks for the notification

**Comment by dmc-8288** [comment]
Hi there,
Thanks for your quick reply.
I am suffering from another problem (Please go through it once). I have uploaded one zip file for you. In that zip folder you will find two code files (MKL-try-3 and MKL-try-4). When I run MKL-try-3 (using sklearn) I don't get any error, it shows me the output, but whenever I try to run the same code with EasyMKl function as shown in MKL-try-4, I get the error as saying;

Traceback (most recent call last):
  File "C:/Users/yubra/PycharmProjects/FRO_COM_NEUROSCI/MKL-CODE-TRy/MKL-try-4.py", line 68, in <module>
    clf1 = clf.fit(X_train, y_train)
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\MKLpy\algorithms\base.py", line 65, in fit
    self._prepare(KL, Y)
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\MKLpy\algorithms\base.py", line 58, in _prepare
    self.KL, self.Y = check_KL_Y(KL,Y)
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\MKLpy\utils\validation.py", line 66, in check_KL_Y
    KL = check_KL(KL)
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\MKLpy\utils\validation.py", line 58, in check_KL
    check_squared(KL[0])
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\MKLpy\utils\validation.py", line 31, in check_squared
    check_array(K)
  File "C:\Users\yubra\Anaconda3\envs\FRO_COM_NEUROSCI_1\lib\site-packages\sklearn\utils\validation.py", line 556, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[2.5781695  3.50904135 2.9517885  2.9519358  3.50891378 2.95198938
 2.95210093 3.5088704  3.50895293 3.50883719 2.95186438 3.50894411
 2.95194918 3.50902544 2.95173438 3.50876015 2.9519695  2.95178601
 3.50895847 3.50926653 1.03961973 2.95191633 2.95209571 1.0396713
 3.33200838 2.95190355 2.95163525 3.33205359 3.50886603 2.95196699
 2.95200147 2.95175799 3.48493449 3.30411415 3.48201502 2.92988108
 3.47990248 1.02861174 3.47834003 3.48379858 3.47438345 3.478586
 3.48432221 2.93096387 3.48224838 3.30813808 3.48426933 3.46642392
 2.9280971  3.48186123 3.47941113 2.92747446 2.92832666 2.92819417
 2.92562444 2.92159013 2.92417815 3.48161812 2.92830958 2.92641703
 3.48098095 3.4754099  3.47435292 2.92645064 3.48468625 3.48613185
 1.03198013 3.47150035].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Process finished with exit code 1

[MKL-CODE-TRy.zip](https://github.com/IvanoLauriola/MKLpy/files/4676606/MKL-CODE-TRy.zip)

Please give me some suggestion.

**Comment by IvanoLauriola** [comment]
Ok, I quickly checked your code, and there are two main errors.

Firstly, in both your files you apply a train_test_split to a kernel. That function (sklearn.model_selection.train_test_split) is not designed to split a kernel, but it can split a samples matrix. The result is really different.

**correct way**
Assume you have **10000** data-points with **100** features.
If you want to split them into training (70%) and test (30%) you can use that method, receiving two samples matrices of 7000x100 and 3000x100.
Then, you can compute the training and test kernels obtaining two kernel matrices of 7000x7000 and 3000x7000.

**what I found in the file**
If you compute the kernel with the whole samples matrix you have a kernel matrix of 10000x10000 entries.
If you pass that matrix to train_test_split you receive two matrices of 7000x10000 and 3000x10000.
You can easily understand that the shapes are wrong, but what happens?
Answer: train_test_split treats the input as a matrix of shape n_samples x n_features, but your kernel is n_samples x n_samples! So you cannot use train_test_split to divide a kernel matrix!

**Additionally**, if you want to use a precomputed kernel with the _sklearn.svm.SVC_ classifier, you need to specify this!

`SVC(C=10, kernel='preocmputed')`

Otherwise, the SVC classifier treats the input as a samples matrix, but in your code the input is supposed to be a kernel. In other words, your code in MKL-try-3.py does not explode when you run it, but the result computed is wrong.
Check the scikit-learn tutorials about how to combine precomputed kernels with GridSearchCV! It may be not trivial.


Concerning the second error, I found that you're passing a single matrix to EasyMKL (remember that here you also have the same split error previously described). A MKL algorithm wants a list of kernels and not a single one.
I suggest you to check out our [tutorials on readthedocs](https://mklpy.readthedocs.io/en/latest/).
Even if the complete documentation is still not available, I think those tutorials are mature enough to clarify your doubts.

Thanks four your notification, your error helps us to improve our error messages and exceptions handling!

**Comment by dmc-8288** [comment]
Hello there, 
Once again thank you for your awesome explanation, your explanation really helped me a lot.
Till today, I was working on a 0.4.3 version, so there was no problem at all for me to load .CSV file and everything was fine. But today while I was trying to use polynomial metrics from MKL, for that I need to upgrade my MKLpy version ton 0.5 or 0.5.1. So, I upgraded it, but now the problem for me is that I can't load the CSV file into it.
So, please would you suggest to me some steps on how to load the CSV file into it in a simple way.
Looking for your reply.

**Comment by IvanoLauriola** [comment]
please provide us additional details i.e. the code that generates the error and the error message.

**Comment by dmc-8288** [comment]
![11111111](https://user-images.githubusercontent.com/65744819/83134784-d18da300-a11f-11ea-8e72-2e3b56579f95.JPG)

[MKL-try-4.zip](https://github.com/IvanoLauriola/MKLpy/files/4695137/MKL-try-4.zip)

Hello there,
As per your suggestion, I have uploaded the code and error message. I am trying to load the dataset but now I can't load it, I don't know why. I can load the same dataset (.CSV) file in 0.4.3 but not in a 0.5. I think the loading method is changed but I am not aware of it. So, please help me with it. 
If you don't mind then can you give me some suggestions for the below question?
 Is it possible to combine 3 or 4 kernels into one? As I am thinking to combine three or four different types of features into one. So do u think it's possible to combine the output of each polynomial kernel with each other? Is it a feasible process or not?

Thank you

**Comment by IvanoLauriola** [comment]
That error is really annoying. I carefully checked the code and tried to replicate the error.
Specifically, I used the latest version of MKLpy with torch 1.5.0.

I tried to read a CSV file to simulate your code, and everything worked.
My suggestion is to check the values of `X1` after 
`X1 = dataset1.iloc[:, 1:].values`
Be sure that `X1` is not an `ndarray` of objects.
In case you can print `X1` and show me the output

**Comment by IvanoLauriola** [comment]
Concerning your last question, yes you can.
MKL is widely used in information fusion to combine kernels (linear, polynomial, or whatever) developed with different feature sets. So basically you can create a kernel for each view of your problem and then you can use a MKL algorithm to combine them.

**Comment by dmc-8288** [comment]
> That error is really annoying. I carefully checked the code and tried to replicate the error.
> Specifically, I used the latest version of MKLpy with torch 1.5.0.
> 
> I tried to read a CSV file to simulate your code, and everything worked.
> My suggestion is to check the values of `X1` after
> `X1 = dataset1.iloc[:, 1:].values`
> Be sure that `X1` is not a `ndarray` of objects.
> In case you can print `X1` and show me the output.
Hello there,
Thanks for your helpful suggestion. I was getting that problem because of the incompatible torch version and after I update it to the latest one (1.5.), now I can load the CSV file.

But now I am getting another problem (actually two types of problems).
I get this problem (Screenshot from 2020-06-01 14-26-29) when I use the homogenous polynomial kernel and this one (Screenshot from 2020-06-01 14-28-58) when I use polynomial kernel.

I didn't understand your previous answer last line (" then you can use an MKL algorithm to combine them").

I try to combine kernel by using; K7 = k1+k2 for a training data and k8 = k11+k22 for a testing dataset, whenever I pass these combined parameters to the cross_val_score function. I get below screenshot error (Additional: this code can be run on 0.4.3 but not on 0.5.1).

At below, I have attached the code and the dataset features.
I don't know what am I doing run.
Please suggest to me.

[a.zip](https://github.com/IvanoLauriola/MKLpy/files/4709627/a.zip)
![Screenshot from 2020-06-01 14-26-29](https://user-images.githubusercontent.com/65744819/83379271-119da000-a416-11ea-9bba-8d5345f9c1c5.png)
![Screenshot from 2020-06-01 14-28-58](https://user-images.githubusercontent.com/65744819/83379276-12cecd00-a416-11ea-9584-5836d42c04af.png)

**Comment by IvanoLauriola** [comment]
I observed that you used multiple times in your code something like `k = k1+k2+k3+...`
That's the key of the problem!
You've made a kernel that is the simple summation of base kernels. Then, you tried to use a MKL algorithm like a simple SVM. The MKL algorithm wants a list of kernels as input and not a single one. 
In other words, you do not have to set the combination (`k7 = k1+k2`) a priori. 
The correct way is
`EasyMKL().fit([k1, k2], Ytr1)`

Does this solve your problem?

**Comment by Alzheimer1** [comment]
Hello there,
I followed your suggestion, but I am still getting the same problem while using polynomial kernel, I get the problem in; scores = cross_val_score(k1, Ytr1, EasyMKL(learner=base_learner, lam=lam), n_folds=5, scoring='accuracy'), whereas while I use homogenous polynomial kernel it gave me error in;  clf = EasyMKL(learner=base_learner, lam=best_results['lam']).fit([k1, k2], Ytr1)

I have attached a screenshot and a code and a dataset too.
Thanks
![polynomial-error](https://user-images.githubusercontent.com/66239303/83400087-3e18e280-a43d-11ea-9200-ae46caca1b35.png)
 and dataset as well.
[a.zip](https://github.com/IvanoLauriola/MKLpy/files/4710734/a.zip)
![homogenous-polynomial-error](https://user-images.githubusercontent.com/66239303/83400083-3ce7b580-a43d-11ea-9da4-87d72438bd0d.png)

**Comment by dmc-8288** [comment]
Hello there,
I followed your suggestion, but I am still getting the same problem while using polynomial kernel, I get the problem in; scores = cross_val_score(k1, Ytr1, EasyMKL(learner=base_learner, lam=lam), n_folds=5, scoring='accuracy'), whereas while I use homogenous polynomial kernel it gave me error in; clf = EasyMKL(learner=base_learner, lam=best_results['lam']).fit([k1, k2], Ytr1)

I have attached a screenshot and a code and a dataset too.
Thanks

[a.zip](https://github.com/IvanoLauriola/MKLpy/files/4710751/a.zip)
![homogenous-polynomial-error](https://user-images.githubusercontent.com/65744819/83400359-a8318780-a43d-11ea-8607-5d585741b6b1.png)
![polynomial-error](https://user-images.githubusercontent.com/65744819/83400363-a962b480-a43d-11ea-9d79-133f6aa4121a.png)

**Comment by IvanoLauriola** [comment]
I tried your code and I found the error.
Basically, in the script `MKL-using-homogenous-polynomial` you define `k1` and `k2` as two lists of kernels. The cross-validation works as you're passing `k1` as input.
However, this instruction
`clf = EasyMKL(learner=base_learner, lam=best_results['lam']).fit([k1, k2], Ytr1)`
contains a mistake. Specifically, your're passing `[k1,k2]` that is a list of lists of kernels, and not a list of kernels.
If you want to use kernels from both `k1` and `k2` you can concatenate the two lists
`clf = EasyMKL(learner=base_learner, lam=best_results['lam']).fit(k1+k2, Ytr1)`

In the other script, i.e. `MKL-using-polynomial` you're using cross-validation with a single kernel and not with a list of kernels (in that script, `k1` is a kernel)
