### ISSUE TITLE
no file dataset_path.svmlight

### ISSUE THREAD

**Issue by bixiu** [IvanoLauriola/MKLpy#15]
hi,i  just run the tutorial which is from  https://mklpy.readthedocs.io/en/latest/examples/examples_loading/,
maybe some dataset i missed

**Comment by IvanoLauriola** [comment]
Hi!
Just replace that string with your svmlight-like file path.
See https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html

You can find examples of svmlight-like files here https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html

**Comment by bixiu** [comment]
> Hi!
> Just replace that string with your svmlight-like file path.
> See https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html
> 
> You can find examples of svmlight-like files here https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html

thank you very much. it is ok.
