### ISSUE TITLE
composite kernel

### ISSUE THREAD

**Issue by palita-s** [IvanoLauriola/MKLpy#21]
First of all, thank you for such useful tool!
I wonder that if I have multiple training and testing feature sets, how can I get the composite kernel of all sets to be used in model training and prediction?
Thank you in advance for your reply :)

**Comment by IvanoLauriola** [comment]
Hi there,
so, you're in a multiview/information fusion setting, right?
In this case, there is not a specific tool, you just need to compute the kernel for each view (i.e. each feature set).

For instance, let's assume we're working with a sentence classification task, and multiple features consist of grammar rules, embedding, and pos. We can do something like this
```
X1 = [grammar_features(sent) for sent in sentences]
X2 = [contextual_word_embedding(sent) for sent in sentences]
X3 = [part_of_speech(sent) for sent in sentences]
```
Be sure that X1[i] corresponds to the same sentence of X2[i] and X3[i]. Then, we can just create a kernel for each view
```
from sklearn.metrics.pairwise import linear_kernel as lin_k
KL = [lin_k(X1), lin_k(X2), lin_k(X3)]
```
and combine them with MKL
```
from MKLpy.algorithms import EasyMKL
clf = EasyMKL().fit(KL, Y)
```

Does this example answer your question?

**Comment by palita-s** [comment]
Thank you for such a clear explanation, I totally understood.

However, when I tried training a classifier, I kept getting ('Wrong shape', torch.Size([311])).
Note that the number of instances is 311, and I tried using MKLpy.metrics.pairwise linear_kernel, sklearn.metrics.pairwise linear_kernel and also calculating kernel by myself, but I still got that error.

**Comment by IvanoLauriola** [comment]
Can you paste a snippet of code to reproduce the error?

Il giorno mar 18 ago 2020 alle ore 22:23 palita-s <notifications@github.com>
ha scritto:

**Comment by palita-s** [comment]
Hi, thank you for your reply. I was wrong passing only one kernel into the function, thus it gave an error. When I ran with 2+ kernels, it was totally fine.

**Comment by IvanoLauriola** [comment]
Copy.
Of course, MKL algorithms need a list of kernels instead of a single one.
However, thanks for your feedback, we'll improve the error messages to simplify the usage!
