### ISSUE TITLE
Python 3 compatibilities & references

### ISSUE THREAD

**Issue by mattvan83** [IvanoLauriola/MKLpy#6]
Hello,

Is this code compatible with Python 3 ?

Would it be possible to have reference publications associated with algorithms ?

**Comment by dominic-z** [comment]
I don't think it can run with Python 3.
The 'import' syntax is incorrect in Python 3.
But.....can this code compatible with Python 2?

**Comment by IvanoLauriola** [comment]
Hi guys,
actually, the cose is not compliant with Python 3 but only with Python 2.
However, a new version will be published as soon as possible, which includes new kernels, algorithms and bug fix

**Comment by mattvan83** [comment]
Hi,
Great news, is thisnew release including upgrade to Python 3 and compliance with sklearn ?
Where could we find references to algorithms ?

**Comment by dswang1234** [comment]
nice project for MKL.
but not fit Python 3 is just a little bad.

**Comment by IvanoLauriola** [comment]
The code has been updated for Python 3!
