### ISSUE TITLE
Tests 

### ISSUE THREAD

**Issue by raamana** [IvanoLauriola/MKLpy#8]
Hi there,

I am considering using this package as part of my work, and would like to know if any of the developers have written any tests for it already? If so, let me know where they are? 

I can also help write some, or improve the existing test suite. I want to coordinate with you if that's possible.

Looking forward to hear you, and use the well-tested version of this package.

Thanks!

**Comment by xinyanliang** [comment]
Did anyone successfully runs the example provided by developer

**Comment by raamana** [comment]
I don't know about others, but I haven't been able to. I am considering writing a new package myself. Follow me - should be releasing it soon.

**Comment by IvanoLauriola** [comment]
Hi,
sorry for the late answer.
We are working on the package.
**Tomorrow** we will update a stable version with sample code

**Comment by IvanoLauriola** [comment]
Hi,
the code has been updated, now the package is compliant with python 3. The examples directory contains some useful scripts!
We will add ASAP the following algorithms: 
- GRAM,
-  MEMO,
- SimpleMKL,
- R-MKL.
