### ISSUE TITLE
clf.weights is None if input is multiclass

### ISSUE THREAD

**Issue by 761328022** [IvanoLauriola/MKLpy#9]
Hello, I'm running the testi_training.py, and change the input to a 3-class dataset, and I encounter a problem from these lines:
`from MKLpy.algorithms import AverageMKL, EasyMKL, KOMD	#KOMD is not a MKL algorithm but a simple kernel machine like the SVM`
`print ('training AverageMKL...', end='')`
`clf = AverageMKL().fit(KLtr,Ytr)	#a wrapper for averaging kernels`
`print ('done')`
`print(clf.weights)			#print the weights of the combination of base kernels`
`K_average = clf.ker_matrix	#the combined kernel matrix`

the clf.weights and K_average is both None. I'n not sure if clf.weights should be changed to clf.clf.weights, and I don't know what to do with K_average. Is this a bug or is it just the way the algorithm is? Thanks in advance for your kind answer.

**Comment by 761328022** [comment]
Thank you for replying so fast! I see it now.

**Comment by IvanoLauriola** [comment]
Fixed!
Now in multiclass settings clf.weights returns a dictionary containing weights for each sub-model. The same for clf.ker_matrix
